### ISSUE TITLE
Your API version does not support fractional size rules. Please upgrade to a minimum version 163. - code: 10285

### ISSUE THREAD

**Issue by davidpellerin** [stoqey/ib#144]
I'm running into a problem trying to retrieve Market Data for Ethereum.  I am able to retrieve market data for normal NASDAQ securities (eg: $SPY).  It seems like possibly the API that `ib` calls might not support fractional results.  Is that the case? Or is it possible that I have some of the "Stock" properties incorrect?

Here's a screenshot of what is happening:

![image](https://user-images.githubusercontent.com/309969/154497789-fc361074-a105-4685-a873-4c93441448bc.png)

**Comment by mfrener** [comment]
Unfortunalty is that easy to add.
TDLR:
This lib is a port of the offical IB Java library, where this https://github.com/stoqey/ib/blob/master/src/core/io/encoder.ts is the Typescript counterpart to this https://github.com/stoqey/ib/blob/master/ref/client/EClient.java and this https://github.com/stoqey/ib/blob/master/src/core/io/decoder.ts the counpart of https://github.com/stoqey/ib/blob/master/ref/client/EClient.java
The files I linked implement communication with gateways up to version 151. Support for factional shares have been added on 163. So to get support for this, you pull  current IB API java client code, diff it with the one on https://github.com/stoqey/ib/blob/master/ref and update the encoder / decoder code, so it supports versions >= 163.

It has been in on my todo list, but hasn't made it further yet (if you know java + ts, maye you can give it try, just need very carefull work because the on decoder / encoder code is very sinsible to read/writing one token too much or less and than it stops working)

**Comment by davidpellerin** [comment]
@mfrener thanks for the detailed explanation. that makes a lot of sense. I will close this issue for now and look into the code.
