### ISSUE TITLE
How to unsubscribe to e.g. getMarketData?

### ISSUE THREAD

**Issue by tomw1808** [stoqey/ib#156]
it might be something extremely obvious, but I just can't wrap my head around, so, apologies for opening a ticket in advance.

I am creating a new subscription to getMarketData - that works fine.

Then I get a subscription object back and so a `.subscribe({next... etc etc})`

I tried to `.unsubscribe()` on that subscription object, that isn't working. 

How to unsubscribe to a market subscription?

**Comment by gitnan** [comment]
Hi @tomw1808, could you post your code please so that I can take a look for you? Could you also confirm if you are using IBApiNext or IBApi? I would assume IBApiNext

**Comment by mfrener** [comment]
Sorry for late response. Yes, .unsubscribe() should it.
Have you called get'MarketData multiple times? Asking because IBApiNext will only create one market data subscription on TWS per contract, even if getMarketData / .subscribe is called multiple times. It will stay subscribed until **all** have unsubscribed.
You can debug this by adding breakpoints here https://github.com/stoqey/ib/blob/035f75aef5442ce99305da657630c5b8421b7aed/src/core/api-next/subscription.ts#L116 (on first observer, start TWS subscription, increase observersCount for every new observer) and here https://github.com/stoqey/ib/blob/035f75aef5442ce99305da657630c5b8421b7aed/src/core/api-next/subscription.ts#L125 (when observer left, decrease observersCount, until it is 0, than unsubscribe on TWS)
