### ISSUE TITLE
open order event decoder error

### ISSUE THREAD

**Issue by Tsopic** [stoqey/ib#34]
After sending an successful order to IB TWS there are 2 issues.

1) I'm not sure how to switch successfully between `preMarket` allowed orders and Afterhours (Outside - RHA or whatev) Premarket orders can be done with IB API order template default value only at this point?

2) After the order is successfully processed. Facing decoder issue. Haven't dug into code yet. 

`Decoding error on decodeMsg_OPEN_ORDER: unprocessed data left on queue. Please report to https://github.com/stoqey/ib - code: 505 - reqId: -1' Error: Decoding error on decodeMsg_OPEN_ORDER: unprocessed data left on queue. Please report to https://github.com/stoqey/ib`

**Comment by mfrener** [comment]
1) Should be Order.outsideRth=true; 
(but note that IB has some very own understanding of regular-trading-hours .. i.e. I'm trading GLOBEX futures, which are open 24/5, but still I need to enable Rth, otherwise order won't get filled outside of NYSE(????) market/pre-market hours.. so if you want to trade outsiede-rth, its probably better to just enable it always via template.. so it's on and nothing can go wrong about it).
2) Try https://github.com/stoqey/ib/commit/162b9ffeb34c51fd42794424baa11442ecdbabc1 
Is it the fix from placeOrder (modelCode was not send) but no now on decoder side (modeCode was not read). Checked the Java code if there mode places were we miss code for MIN_SERVER_VER.MODELS_SUPPORT, but placeOrder and openOrder are only places and both fixed now.
